local assert = require('luassert')
local tartar_lsp = require('tartar.lsp')

describe('lsp', function()
  local bufnr = vim.api.nvim_get_current_buf()

  describe('.has_clients()', function()
    it('returns false if there are no clients attached to the buffer', function()
      assert.is_false(tartar_lsp.has_clients(bufnr))
    end)
  end)

  describe('.buf_get_clients()', function()
    it('returns an empty table if there are no clients attached to the buffer', function()
      local clients = tartar_lsp.buf_get_clients()
      assert.is_table(clients)
      assert.is.equal(clients.count, 0)
      assert.is_table(clients.names)
      assert.is_table(clients.ids)
    end)
  end)

  describe('.buf_detach_clients()', function()
    it('does not throw an error if there are no clients attached to the buffer', function()
      local clients = tartar_lsp.buf_get_clients()
      assert.is_table(clients)
      tartar_lsp.buf_detach_clients(clients)
    end)
  end)
end)
