local assert = require('luassert')
local stub = require('luassert.stub')
local timer = require('tartar.timer')

describe('.set_timer()', function()
  local t
  local s
  before_each(function()
    t = timer.set_timer()
    s = stub(vim, 'schedule')
  end)

  it('not called if a negative number is specified for the "debounce" method', function()
    t.debounce(-1, function() end)
    vim.wait(100)
    assert.stub(s).was.called(0)
  end)

  it('"debounce" method must be reset if it is called again before the "timeout"', function()
    t.debounce(50, function() end)
    assert.stub(s).was.called(0)
    vim.wait(20)
    t.debounce(50, function() end)
    vim.wait(20)
    t.debounce(50, function() end)
    vim.wait(20)
    assert.stub(s).was.called(0)
    vim.wait(30)
    assert.stub(s).was.called(1)
  end)

  it('"stop" method stops the timer', function()
    t.debounce(50, function() end)
    t:stop()
    assert.is.equal(t:_closing(), false)
    vim.wait(100)
    assert.stub(s).was.called(0)
  end)

  it('"close" method stops the timer', function()
    t.debounce(50, function() end)
    assert.is.equal(t:_closing(), false)
    t:close()
    assert.is.equal(t:_closing(), true)
    vim.wait(100)
    assert.stub(s).was.called(0)
  end)
end)
